// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaafchljkvriwwvevtuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhYWZjaGxqa3ZyaXd3dmV2dHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0MDUyODQsImV4cCI6MjA1MDk4MTI4NH0.y45yMpd2tn8Ds-Ahz-ZjlWd-3-XlQTDbU2P4P3Ci5fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);